// gestionStock-frontend/src/pages/Liste_produits.jsx
import React from "react";
import { useState, useEffect } from "react";
import { useProduitcontext } from "../Contexts/Contexteproduit";
import {
  PencilIcon,
  TrashIcon,
} from "../../node_modules/@heroicons/react/24/solid";

function Liste_produits() {
  const { produits, addProduit, supprimerProduit, error, loading } =
    useProduitcontext();

  return (
    <div className="affichage_produits">
      {loading ? (
        <div className="loading">Loading...</div>
      ) : (
        <div>
          <h1 className="text-centertext-4xl font-bold text-center mb-6 text-gray-800">
            Liste des Produits
          </h1>
          {error && <div style={{ color: "red" }}>Erreur : {error}</div>}
          <table className="custom-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Quantité</th>
                <th>Prix</th>
              </tr>
            </thead>
            <tbody>
              {produits.map((produit) => (
                <tr key={produit.id}>
                  <td>{produit.id}</td>
                  <td>{produit.nom}</td>
                  <td>{produit.stock}</td>
                  <td>{produit.prixVente}</td>
                  <div>
                    <button className="flex items-center px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 focus:outline-none">
                      {" "}
                      <PencilIcon className="h-5 w-5 mr-1" />
                    </button>{" "}
                    <button className="flex items-center px-3 py-2 bg-red-500 text-white rounded hover:bg-red-600 focus:outline-none">
                      <TrashIcon className="h-5 w-5 mr-1" />
                    </button>
                  </div>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default Liste_produits;

// gestionStock-frontend/src/app/pages/liste-produits/liste-produits.component.ts
import { Component, computed, inject, resource, signal } from '@angular/core';
import { ProduitService } from '../../services/api.service';
import { CommonModule } from '@angular/common';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Produit } from '../../model/produit.model';

@Component({
  selector: 'app-liste-produits',
  imports: [CommonModule, MatProgressSpinnerModule],
  templateUrl: './liste-produits.component.html',
  styleUrl: './liste-produits.component.css',
})
export class ListeProduitsComponent {
  apiService = inject(ProduitService);
  produitsRessource = resource({ loader: () => this.apiService.getProduits() });
  deleting = signal(false);

  loading = computed(
    () => this.deleting() || this.produitsRessource.isLoading()
  );

  async deleteProduit(id: number): Promise<void> {
    await this.apiService.deleteProduit(id);
    this.produitsRessource.reload();
  }
  async updateProduit(id: number, newProduit : Produit): Promise<void> {
    await this.apiService.updateProduit(id,newProduit);
    this.produitsRessource.reload();
  }

}

<div class="affichage_produits">
      <div>
        <h1 class="text-center text-4xl font-bold text-center mb-6 text-gray-800">
          Liste des Produits
        </h1>


        <table class="custom-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nom</th>
              <th>Quantité</th>
              <th>Prix</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let produit of produitsRessource.value()">
                <td>{{produit.id}}</td>
                <td>{{produit.nom}}</td>
                <td>{{produit.stock}}</td>
                <td>{{produit.prixVente}}</td>
                <div>
                  <td>
                    <button
                      class="flex items-center px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 focus:outline-none"
                      
                    >
                      Modifier
                    </button>
                    <button
                      class="flex items-center px-3 py-2 bg-red-500 text-white rounded hover:bg-red-600 focus:outline-none"
                      (click)="deleteProduit(produit.id)"
                    >
                    Supprimer
                    </button>
                    
                  </td>
                </div>
              </tr>
            
            
        </table>
      </div>
    
  </div>
  @if (loading()) {
    <mat-progress-spinner
      mode="indeterminate"
      diameter="50"
    ></mat-progress-spinner>
    }
